<a href="https://colab.research.google.com/github/tensorbytes0202/Deep-learning/blob/main/Backpropogation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd

In [33]:
df = pd.DataFrame([[8,8,9],[7,9,5],[6,10,6],[5,12,7]], columns = ['cgpa','profile_score','lpa'])


In [34]:
df

cgpa  profile_score  lpa
0     8              8    9
1     7              9    5
2     6             10    6
3     5             12    7

In [35]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):
    parameters['W' +str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b' +str(l)] = np.zeros((layer_dims[l],1))

  return parameters

In [36]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [37]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

In [38]:
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters) //2
  for l in range(1,L+1):
    A_prev = A
    Wl = parameters['W' +str(l)]
    bl = parameters['b' +str(l)]

    A = linear_forward(A_prev,Wl,bl)

  return A,A_prev


In [39]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [40]:
y_hat,A1

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [41]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [42]:
y_hat = y_hat[0][0]

In [43]:
A1

array([[1.6],
       [1.6]])

In [44]:
update_parameters(parameters,y,y_hat,A1,X)

In [45]:
parameters

{'W1': array([[0.11774553, 0.11774553],
        [0.11774553, 0.11774553]]),
 'b1': array([[0.00221819],
        [0.00221819]]),
 'W2': array([[0.127776],
        [0.127776]]),
 'b2': array([[0.145136]])}

In [46]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [47]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11774553, 0.11774553],
        [0.11774553, 0.11774553]]),
 'b1': array([[0.00221819],
        [0.00221819]]),
 'W2': array([[0.127776],
        [0.127776]]),
 'b2': array([[0.145136]])}

In [48]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12657784, 0.12910136],
        [0.12657784, 0.12910136]]),
 'b1': array([[0.00347995],
        [0.00347995]]),
 'W2': array([[0.14427169],
        [0.14427169]]),
 'b2': array([[0.1530174]])}

In [49]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.13721706, 0.15463548],
        [0.13725024, 0.15471512]]),
 'b1': array([[0.00560779],
        [0.00561443]]),
 'W2': array([[0.1710789 ],
        [0.17161248]]),
 'b2': array([[0.18405027]])}

In [50]:
# Epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5
for i in range(epochs):
  Loss = []

  for j in range(df.shape[0]):
    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]



    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters


Epoch -  1 Loss -  39.5890758702848
Epoch -  2 Loss -  27.113318964877806
Epoch -  3 Loss -  12.313622956777877
Epoch -  4 Loss -  4.770604481426034
Epoch -  5 Loss -  3.224430150751154


{'W1': array([[0.31794399, 0.40089875],
        [0.3329432 , 0.42096775]]),
 'b1': array([[0.03191211],
        [0.03406663]]),
 'W2': array([[0.45474097],
        [0.51564622]]),
 'b2': array([[0.51645254]])}